/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.CandidatoDAO;
import DAO.PartidoDAO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows
 */
public class CandidatoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form CandidatoVIU
     */
    public CandidatoVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCandidatos = new javax.swing.JTable();
        txtRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        rbNome = new javax.swing.JRadioButton();
        rbNumero = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cbPartido = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Candidatos");
        setResizable(false);
        setSize(new java.awt.Dimension(862, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIncluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/symbol_add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIncluirMousePressed(evt);
            }
        });
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 30));

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/symbol_refresh.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setMaximumSize(new java.awt.Dimension(97, 33));
        btnAlterar.setMinimumSize(new java.awt.Dimension(97, 33));
        btnAlterar.setPreferredSize(new java.awt.Dimension(97, 33));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAlterarMousePressed(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 140, 30));

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/symbol_restricted.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExcluirMousePressed(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 140, 30));

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_left.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSairMousePressed(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 90, -1));

        tbCandidatos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCandidatos.setToolTipText("");
        tbCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbCandidatosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbCandidatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 590, 200));

        txtRegistro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRegistro.setText("txtRegistro");
        jPanel1.add(txtRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Registros encontrados:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Candidatos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        jPanel1.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 145, -1));

        buttonGroup1.add(rbNome);
        rbNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNome.setText("Pesquisar por nome");
        rbNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbNomeMousePressed(evt);
            }
        });
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });
        jPanel1.add(rbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        buttonGroup1.add(rbNumero);
        rbNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbNumero.setText("Pesquisar por número");
        rbNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbNumeroMousePressed(evt);
            }
        });
        rbNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(rbNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 163, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Número: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 71, -1));

        cbPartido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbPartido.setToolTipText("");
        cbPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbPartidoMousePressed(evt);
            }
        });
        cbPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPartidoActionPerformed(evt);
            }
        });
        jPanel1.add(cbPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Partido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirMousePressed
        CandidatoDAO dAO = new CandidatoDAO();
        String nome = txtNome.getText();
        int numero = Integer.valueOf(txtNumero.getText());
        String partido = cbPartido.getSelectedItem().toString();

        dAO.incluirCandidatos(nome, numero, partido);

        ResultSet rs = dAO.obterCandidatos();
        carregarTabelaCandidatos(rs);
    }//GEN-LAST:event_btnIncluirMousePressed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMousePressed

        //obtendo os dados da alteração
        CandidatoDAO dDAO = new CandidatoDAO();
        int linhaSelecionada = tbCandidatos.getSelectedRow();

        if(linhaSelecionada >= 0){

            int codigo = Integer.parseInt(tbCandidatos.getModel().getValueAt(linhaSelecionada, 0).toString());
            String nome = txtNome.getText();
            int numero = Integer.valueOf(txtNumero.getText());
            String partido = cbPartido.getSelectedItem().toString();

            dDAO.alterarCandidatos(codigo, nome, numero, partido);

            ResultSet rs = dDAO.obterCandidatos();
            carregarTabelaCandidatos(rs);
        }

        else
            JOptionPane.showMessageDialog(null, "Clique em alguma linha da tabela para poder alterar !");
    }//GEN-LAST:event_btnAlterarMousePressed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMousePressed
        CandidatoDAO dDAO = new CandidatoDAO();
        int linhaSelecionada = tbCandidatos.getSelectedRow();

        if(linhaSelecionada >=0)
        {
            int codigo = Integer.parseInt(tbCandidatos.getModel().getValueAt(linhaSelecionada, 0).toString());

            dDAO.excluirCandidatos(codigo);

            ResultSet rs = dDAO.obterCandidatos();
            carregarTabelaCandidatos(rs);

        }
        else
        JOptionPane.showMessageDialog(null, "Clique em alguma linha da tabela para poder EXCLUIR !");
    }//GEN-LAST:event_btnExcluirMousePressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMousePressed
        dispose();
    }//GEN-LAST:event_btnSairMousePressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void tbCandidatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCandidatosMousePressed
        //numero da linha que está sendo selecionada na tabela
        int linhaSelecionada = tbCandidatos.getSelectedRow();

        //0 é a primeira coluna da tabela (código, que não será alterado)
        String nome = tbCandidatos.getModel().getValueAt(linhaSelecionada, 1).toString();
        String numero = tbCandidatos.getModel().getValueAt(linhaSelecionada, 2).toString();
        String partido = tbCandidatos.getModel().getValueAt(linhaSelecionada, 3).toString();

        txtNumero.setText(nome);
        txtNome.setText(numero);
        cbPartido.getSelectedItem().toString();

    }//GEN-LAST:event_tbCandidatosMousePressed

    private void cbPartidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPartidoMousePressed

    }//GEN-LAST:event_cbPartidoMousePressed

    private void cbPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPartidoActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      CandidatoDAO dDAO = new CandidatoDAO();
        PartidoDAO dAO2 = new PartidoDAO();
        
        ResultSet rs = dDAO.obterCandidatos();        
        ResultSet rs2 = dAO2.obterPartidos();
        
        
        carregarTabelaCandidatos(rs);       
        carregarComboPartidos(rs2); 
        
        if((!rbNome.isSelected())&&(!rbNumero.isSelected())){
            txtPesquisar.setEnabled(false);
        }
       
            
    }//GEN-LAST:event_formWindowOpened

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
  
        CandidatoDAO dAO = new CandidatoDAO();
        ResultSet rs = null;
        
                
        
        
        if(rbNome.isSelected()){
           rs = dAO.pesquisarCandidatoPorNome(txtPesquisar.getText());
           
        }
        
        if(rbNumero.isSelected()){
            try {
                rs = dAO.pesquisarCandidatoPorNumero(Integer.parseInt(txtPesquisar.getText()));
            } catch (Exception e) {
                rs = dAO.obterCandidatos();
            }
           
         
        }               
               carregarTabelaCandidatos(rs); 
        
        
        
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void rbNomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNomeMousePressed
  
        
        txtPesquisar.setEnabled(true);
        
    }//GEN-LAST:event_rbNomeMousePressed

    private void rbNumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNumeroMousePressed
       
        txtPesquisar.setEnabled(true);
        
        
    }//GEN-LAST:event_rbNumeroMousePressed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNumeroActionPerformed

    
    
    
    public void carregarTabelaCandidatos(ResultSet rs) {
        String colunas[] = new String[]{"Código", "Número", "Nome", "Partido", "Votos"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunas){  
            public boolean isCellEditable(int rowIndex, int mColIndex) {  //evita editar conteúdo das células
                return false;  
            }  
        };//null são as linhas ainda não preenchidas
        tbCandidatos.setModel(modeloTabela);
        int contador = 0;
        
//        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();  
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();  
//        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();  
  
//        esquerda.setHorizontalAlignment(SwingConstants.LEFT);  
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);  
//        direita.setHorizontalAlignment(SwingConstants.RIGHT);  
        
tbCandidatos.getColumnModel().getColumn(0).setCellRenderer(centralizado);  
tbCandidatos.getColumnModel().getColumn(1).setCellRenderer(centralizado);  
tbCandidatos.getColumnModel().getColumn(2).setCellRenderer(centralizado);
tbCandidatos.getColumnModel().getColumn(3).setCellRenderer(centralizado);  
tbCandidatos.getColumnModel().getColumn(4).setCellRenderer(centralizado);  



        
        try {
            while (rs.next()) {
                String linha[] = new String[]{
                    rs.getString("codigo"),
                    rs.getString("numero"),
                    rs.getString("nome"),
                    rs.getString("partido"),
                    rs.getString("votos")                      
                };
                modeloTabela.addRow(linha);
                contador = contador+1;
            }
        } catch (Exception e) {
            System.out.println("Erro ao carregar tabela: " + e.getMessage());
        }

        txtRegistro.setText("" + contador);
                
        
    } 
    
    public void carregarComboPartidos(ResultSet rs) {
        PartidoDAO dAO2 = new PartidoDAO();
        
        try {           
            while(rs.next()) { 
                
                PartidoDAO partidoDAO = new PartidoDAO();
                String linha[] = new String[]{                    
                    rs.getString("nome")                    
                };              
               
               cbPartido.addItem(rs.getString("nome"));
            }      
            
        }        
        catch (Exception e) {
            System.out.println("Erro ao carregar nome: " + e.getMessage());            
        }       
    }  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidatoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbNumero;
    private javax.swing.JTable tbCandidatos;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JLabel txtRegistro;
    // End of variables declaration//GEN-END:variables
}
