/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import MODEL.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class MenuVIEW extends javax.swing.JFrame {

    /**
     * Creates new form MenuVIEW
     */
    public MenuVIEW() {
        initComponents();          
    }
    
    
String nivelUsuario = Usuario.nivel;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTipoUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnResultados = new javax.swing.JButton();
        btnCadastroCandidatos = new javax.swing.JButton();
        btnCadastroPartidos = new javax.swing.JButton();
        btnCadastroUsuarios = new javax.swing.JButton();
        btnVotacao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        iconeTipoUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setText("Principal");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Logado como: ");

        txtTipoUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnResultados.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/prancheta.png"))); // NOI18N
        btnResultados.setText("Resultados");
        btnResultados.setFocusable(false);
        btnResultados.setPreferredSize(new java.awt.Dimension(175, 51));
        btnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResultadosMousePressed(evt);
            }
        });
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        btnCadastroCandidatos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastroCandidatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/workers3(4)_1.png"))); // NOI18N
        btnCadastroCandidatos.setText("Candidatos");
        btnCadastroCandidatos.setFocusable(false);
        btnCadastroCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadastroCandidatosMousePressed(evt);
            }
        });
        btnCadastroCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroCandidatosActionPerformed(evt);
            }
        });

        btnCadastroPartidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastroPartidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/flag png icon1.png"))); // NOI18N
        btnCadastroPartidos.setText("Partidos");
        btnCadastroPartidos.setFocusable(false);
        btnCadastroPartidos.setPreferredSize(new java.awt.Dimension(175, 51));
        btnCadastroPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadastroPartidosMousePressed(evt);
            }
        });
        btnCadastroPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPartidosActionPerformed(evt);
            }
        });

        btnCadastroUsuarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/msn1.png"))); // NOI18N
        btnCadastroUsuarios.setText("Usuários   ");
        btnCadastroUsuarios.setFocusable(false);
        btnCadastroUsuarios.setPreferredSize(new java.awt.Dimension(175, 51));
        btnCadastroUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadastroUsuariosMousePressed(evt);
            }
        });
        btnCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsuariosActionPerformed(evt);
            }
        });

        btnVotacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVotacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voting-and-1.png"))); // NOI18N
        btnVotacao.setText("Votação   ");
        btnVotacao.setFocusable(false);
        btnVotacao.setPreferredSize(new java.awt.Dimension(175, 51));
        btnVotacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVotacaoMousePressed(evt);
            }
        });
        btnVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastroCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastroPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroCandidatos)
                    .addComponent(btnCadastroPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnVotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_left.png"))); // NOI18N
        jButton6.setText("Sair");
        jButton6.setFocusable(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        iconeTipoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(iconeTipoUsuario)
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeTipoUsuario)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnCadastroPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroPartidosActionPerformed

    private void btnVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVotacaoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroUsuariosActionPerformed

    private void btnCadastroPartidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroPartidosMousePressed

        if(btnCadastroPartidos.isEnabled()){
        PartidoVIEW partidoVIEW = new PartidoVIEW();       
        partidoVIEW.setVisible(true);
        }
        
    }//GEN-LAST:event_btnCadastroPartidosMousePressed

    private void btnCadastroUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroUsuariosMousePressed
if(btnCadastroUsuarios.isEnabled()){
       UsuarioVIEW usuarioVIEW = new UsuarioVIEW();       
       usuarioVIEW.setVisible(true);
}
    }//GEN-LAST:event_btnCadastroUsuariosMousePressed

    private void btnVotacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVotacaoMousePressed
        if(btnVotacao.isEnabled()){
        VotacaoVIEW votacaoVIEW = new VotacaoVIEW();       
        votacaoVIEW.setVisible(true);
        }
    }//GEN-LAST:event_btnVotacaoMousePressed

    private void btnResultadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultadosMousePressed
        if(btnResultados.isEnabled()){
        ResultadosVIEW resultadoVIEW = new ResultadosVIEW();       
        resultadoVIEW.setVisible(true);
      }
    }//GEN-LAST:event_btnResultadosMousePressed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
   if(JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Aviso",JOptionPane.YES_NO_OPTION)==0){
    dispose();   
   }       
        
    }//GEN-LAST:event_jButton6MousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        LoginVIEW loginView = new LoginVIEW();
        
        loginView.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void btnCadastroCandidatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroCandidatosMousePressed
    if(btnCadastroCandidatos.isEnabled()){
    CandidatoVIEW candidatoVIEW = new CandidatoVIEW();
    candidatoVIEW.setVisible(true);
    
  
    }
    }//GEN-LAST:event_btnCadastroCandidatosMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try{
        txtTipoUsuario.setText(Usuario.nivel);
        
if(Usuario.nivel.equals("Usuário")){
    btnCadastroCandidatos.setEnabled(false);
    btnCadastroPartidos.setEnabled(false);
    btnCadastroUsuarios.setEnabled(false);
    btnResultados.setEnabled(false); 
   
    iconeTipoUsuario.setIcon(new ImageIcon("src/imagens/user.png"));
    iconeTipoUsuario.setText("");
    
}
else if(Usuario.nivel.equals("Administrador"))
{
    iconeTipoUsuario.setIcon(new ImageIcon("src/imagens/admin.png"));
iconeTipoUsuario.setText("");
btnVotacao.setEnabled(false);
        }
        }
        catch(Exception ex){
            System.out.println("nivelUsuario e Usuario.nivel nulos");
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnCadastroCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroCandidatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroCandidatosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCandidatos;
    private javax.swing.JButton btnCadastroPartidos;
    private javax.swing.JButton btnCadastroUsuarios;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnVotacao;
    private javax.swing.JLabel iconeTipoUsuario;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
