/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VIEW;

import MODEL.LimiteDigitos;
import DAO.BrancoDAO;
import DAO.CandidatoDAO;
import DAO.NuloDAO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class VotacaoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form VotacaoVIEW
     */
    public VotacaoVIEW() {
        initComponents();   
        LimiteDigitos lim = new LimiteDigitos(2); // new LimiteDigitos() quantidade que estiver dentro do  
        txtNumeroCandidato.setDocument(lim);      //parênteses é o limite de dígitos do campo txtNumeroCandidato.        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtNomeCandidato = new javax.swing.JLabel();
        txtNumeroCandidato = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Votação");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setText("Votação");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Digite o número do candidato:");

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_left.png"))); // NOI18N
        jButton3.setText("Sair   ");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtNomeCandidato.setBackground(new java.awt.Color(255, 255, 102));
        txtNomeCandidato.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNomeCandidato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNomeCandidato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNomeCandidato.setOpaque(true);

        txtNumeroCandidato.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNumeroCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCandidatoActionPerformed(evt);
            }
        });
        txtNumeroCandidato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroCandidatoKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/symbol_check_white.png"))); // NOI18N
        jButton2.setText("Branco");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/symbol_check.png"))); // NOI18N
        jButton1.setText("Confirma");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(292, 292, 292))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(txtNumeroCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(txtNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroCandidatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCandidatoKeyReleased
        try{
            CandidatoDAO dAO = new CandidatoDAO();//Faz com que o método "carregarNomeCandidato" reconheça
            //que está chamando o método pesquisarCandidatoPorNumero
            //dentro da classe CandidatoDAO usando o parâmetro rs que está sendo retornado
            ResultSet rs = null;

            rs = dAO.pesquisarCandidatoPorNumero(Integer.parseInt(txtNumeroCandidato.getText()));

            carregarNomeCandidato(rs);
        }

        catch(NumberFormatException ex){
            System.out.println("Entrada inválida !");
            txtNomeCandidato.setText("");
        }

        }

        public void carregarNomeCandidato(ResultSet rs) {

            try {
                if (rs.next()) {
                    String linha[] = new String[]{
                        rs.getString("codigo"),
                        rs.getString("nome"),
                        rs.getString("votos")
                    };
                    codigoFiltrado = (rs.getInt("codigo"));
                    nomeFiltrado = (rs.getString("nome"));
                    votoFiltrado = (rs.getInt("votos"));
                    txtNomeCandidato.setText(nomeFiltrado);

                }
                else
                txtNomeCandidato.setText("");
            }
            catch (Exception e) {
                System.out.println("Erro ao carregar nome: " + e.getMessage());
            }
        }

        public void carregarQuantidadeVotoBranco(ResultSet rs) {

            try {
                while(rs.next()) {
                    String linha[] = new String[]{
                        rs.getString("votoBranco")
                    };

                    votoBrancoFiltrado = (rs.getInt("votoBranco"));
                }

            }
            catch (Exception e) {
                System.out.println("Erro ao carregar nome: " + e.getMessage());
            }
    }//GEN-LAST:event_txtNumeroCandidatoKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        dispose();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        //OBTENDO A QUANTIDADE ATUAL DE VOTOS EM BRANCO do campo votoBranco
        try{
            BrancoDAO dAO = new BrancoDAO();//Faz com que o método "carregarNomeCandidato" reconheça
            //que está chamando o método pesquisarCandidatoPorNumero
            //dentro da classe CandidatoDAO usando o parâmetro rs que está sendo retornado
            ResultSet rs = null;

            rs = dAO.obterVotosBrancos();

            carregarQuantidadeVotoBranco(rs);
        }
        catch(NumberFormatException ex){
            System.out.println("Erro: " + ex.getMessage());

        }

        //MANIPULANDO O BRANCO DE ACORDO COM A QUANTIDADE DO CAMPO votoBranco
        try{
            BrancoDAO dAO2 = new BrancoDAO();
            ResultSet rs = null;
            int votoBranco = 1;
            int codigo = 1;

            rs = dAO2.obterVotosBrancos();

            if(rs.next()) // se o ResultSet rs tiver algum nenhum resultado encontrado

            {
                //obtendo os dados da alteração
                BrancoDAO dDAO = new BrancoDAO();

                int votosTotaisBrancos = votoBrancoFiltrado;
                int votos = votosTotaisBrancos +1;

                dDAO.alterarQuantidadeVotoBranco(votos);
                JOptionPane.showMessageDialog(null, "Voto em branco sucedido!");
                txtNumeroCandidato.setText("");
                txtNomeCandidato.setText("");
            }
            else // se o ResultSet rs NÃO encontrar nenhum resultado.

            dAO2.incluirVotosBrancos(codigo, votoBranco);
        }
        catch(Exception ex){
            System.out.println("Erro: " + ex.getMessage());
        }
        txtNumeroCandidato.requestFocus();
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed

        try{
            CandidatoDAO dAO2 = new CandidatoDAO();
            ResultSet rs = null;

            rs = dAO2.pesquisarCandidatoPorNumero(Integer.parseInt(txtNumeroCandidato.getText()));

            if(rs.next()) // se o ResultSet rs tiver algum nenhum resultado encontrado

            {
                //obtendo os dados da alteração
                CandidatoDAO dDAO = new CandidatoDAO();

                int codigo = codigoFiltrado;
                int votosTotais = votoFiltrado;
                int votos = votosTotais +1;

                dDAO.atualizarVotos(codigo, votos);
                txtNumeroCandidato.setText("");
                txtNomeCandidato.setText("");
                txtNumeroCandidato.requestFocus();
            }
            else // se o ResultSet rs NÃO encontrar nenhum resultado.
            {
                if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja ANULAR o voto?", "ALERTA !",JOptionPane.YES_NO_OPTION)==1){
                return ;
                }
                else {
                
                //OBTENDO A QUANTIDADE ATUAL DE VOTOS EM NULO do campo votoNulo
                try{
                    NuloDAO dAO = new NuloDAO();//Faz com que o método "carregarNomeCandidato" reconheça
                    //que está chamando o método pesquisarCandidatoPorNumero
                    //dentro da classe CandidatoDAO usando o parâmetro rs que está sendo retornado
                    ResultSet rs1 = null;

                    rs1 = dAO.obterVotosNulos();

                    carregarQuantidadeVotoNulo(rs1);
                }
                catch(NumberFormatException ex){
                    System.out.println("Erro: " + ex.getMessage());

                }

                //MANIPULANDO O NULO DE ACORDO COM A QUANTIDADE DO CAMPO votoNulo
                try{
                    NuloDAO dAO1 = new NuloDAO();
                    ResultSet rs1 = null;
                    int votoNulo = 1;
                    int codigo = 1;

                    rs = dAO1.obterVotosNulos();

                    if(rs.next()) // se o ResultSet rs tiver algum nenhum resultado encontrado
                                //será apenas acrescentado, invés de ser criado um novo objeto "nulo"
                    {
                        //obtendo os dados da alteração
                        NuloDAO dDAO = new NuloDAO();

                        int votosTotaisNulos = votoNuloFiltrado;
                        int votos = votosTotaisNulos +1;

                        dDAO.alterarQuantidadeVotoNulo(votos);
                        JOptionPane.showMessageDialog(null, "Voto ANULADO com sucesso!");
                        txtNumeroCandidato.setText("");
                        txtNomeCandidato.setText("");
                        txtNumeroCandidato.requestFocus();
                    }
                    else //se o ResultSet rs NÃO encontrar nenhum resultado o objeto será criado e o voto adicionado.

                    dAO1.incluirVotosNulos(codigo, votoNulo);
                }
                catch(Exception ex){
                    System.out.println("Erro: " + ex.getMessage());
                }
            }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Digite o número do candidato !\n\n Ou um número qualquer, caso queira anular o voto !");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void txtNumeroCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCandidatoActionPerformed

    int codigoFiltrado;
    int votoFiltrado;
    int votoBrancoFiltrado;
    int votoNuloFiltrado;    
    String nomeFiltrado;
    
    
       
   
   public void carregarQuantidadeVotoNulo(ResultSet rs) {
            
        try {           
            while(rs.next()) {                 
                String linha[] = new String[]{                    
                    rs.getString("votoNulo")                    
                };
              
              votoNuloFiltrado = (rs.getInt("votoNulo"));             
            }
                      
        } 
        catch (Exception e) {
            System.out.println("Erro ao carregar nome: " + e.getMessage());            
        }       
    }
    
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotacaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotacaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotacaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotacaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotacaoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtNomeCandidato;
    private javax.swing.JTextField txtNumeroCandidato;
    // End of variables declaration//GEN-END:variables
}
